### PR TITLE
Merge branch 'master' of https://github.com/sap9433/continuouslearning

### PR DESCRIPTION
**Pull request by karthicrajakumar**

### CODE REVIEW

**Comment by sap9433** [comment]
If we do thos change page content will be hidden . Left part is  taken by menu , hence this style to inner container . Please send me screen shots what do you want to achieve by  deleting this , and why .

**Comment by karthicrajakumar** [comment]
the issue you have in prod where the login and signup are caused by this. use some other class if you want to move content. And maybe keep the left and top as % of viewport so it's not static for all screens.

**Comment by sap9433** [comment]
Yah.. ill do that.. cool.

**Comment by karthicrajakumar** [comment]
merge it with master.

**Comment by sap9433** [comment]
As I said , if we just remove that , all other pages we break. So it needed a different fix , which I already did , and pushed to master.

**Pull request closed without merging**
